# Generated by Django 5.2.17 on 2026-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_categoria_id_alter_produto_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoqueMinimo',
            new_name='estoque_minimo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='precoCusto',
            new_name='preco_custo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='precoVenda',
            new_name='preco_venda',
        ),
    ]
