# Generated by Django 5.2.17 on 2026-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_alter_itemvenda_id_alter_venda_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemvenda',
            old_name='precoUnitario',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='itemvenda',
            old_name='subPreco',
            new_name='sub_preco',
        ),
    ]
