# Generated by Django 6.1 on 2026-08-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAbertura', models.DateTimeField(auto_now_add=True)),
                ('dataFechamento', models.DateTimeField(blank=True, null=True)),
                ('valorInicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valorFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'aberto'), ('FECHADO', 'fechado')], default='ABERTO', max_length=10)),
                ('usuarioAbertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caixa_abertos', to=settings.AUTH_USER_MODEL)),
                ('usuarioFechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixa_fechados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'entrada'), ('SAIDA', 'saida')], max_length=10)),
                ('formaPagamento', models.CharField(choices=[('DINHEIRO', 'dinheiro'), ('PIX', 'pix'), ('CARTAO', 'cartao'), ('OUTRO', 'outro')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caixas', to='caixa.caixa')),
            ],
        ),
    ]
