# Generated by Django 5.2.17 on 2026-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_alter_caixa_id_alter_movimentocaixa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='dataAbertura',
            new_name='data_abertura',
        ),
        migrations.RenameField(
            model_name='caixa',
            old_name='dataFechamento',
            new_name='data_fechamento',
        ),
        migrations.RenameField(
            model_name='caixa',
            old_name='usuarioAbertura',
            new_name='usuario_abertura',
        ),
        migrations.RenameField(
            model_name='caixa',
            old_name='usuarioFechamento',
            new_name='usuario_fechamento',
        ),
        migrations.RenameField(
            model_name='caixa',
            old_name='valorFinal',
            new_name='valor_final',
        ),
        migrations.RenameField(
            model_name='caixa',
            old_name='valorInicial',
            new_name='valor_inicial',
        ),
        migrations.RenameField(
            model_name='movimentocaixa',
            old_name='formaPagamento',
            new_name='forma_pagamento',
        ),
    ]
