# Generated by Django 6.1 on 2026-08-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('limiteCrediario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.CharField(blank=True, max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='crediario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveBigIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataVencimento', models.DateField()),
                ('dataPagamento', models.DateField(blank=True, null=True)),
                ('paga', models.BooleanField(default=False)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas', to='crediario.credito')),
            ],
        ),
    ]
