# Generated by Django 5.2.17 on 2026-08-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crediario', '0002_alter_cliente_id_alter_credito_id_alter_parcela_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='limiteCrediario',
            new_name='limite_crediario',
        ),
        migrations.RenameField(
            model_name='credito',
            old_name='valorTotal',
            new_name='valor_total',
        ),
        migrations.RenameField(
            model_name='parcela',
            old_name='dataPagamento',
            new_name='data_pagamento',
        ),
        migrations.RenameField(
            model_name='parcela',
            old_name='dataVencimento',
            new_name='data_vencimento',
        ),
    ]
